# Generated by Django 4.1.5 on 2023-02-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0003_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
