# Generated by Django 4.1.5 on 2023-02-23 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyVerse',
        ),
    ]
